
- name: add repo
  become: true
  apt_repository:
    repo: 'ppa:mmk2410/eclipse-ide-java'
    update_cache: yes

- name: install packages
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - eclipse-ide-java
    - maven