
- name: download golang
  get_url:
    url: "https://dl.google.com/go/go{{ go_version_target }}.linux-amd64.tar.gz"
    dest: "/usr/local/src/go{{ go_version_target }}.linux-amd64.tar.gz"
  become: true

- name: get current version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: remove old installation
  file:
    path: /usr/local/go
    state: absent
  when: go_version is failed or go_version.stdout != go_version_target
  become: true

- name: extract go
  unarchive:
    src: "/usr/local/src/go{{ go_version_target }}.linux-amd64.tar.gz"
    dest: /usr/local
    copy: no
  when: go_version is failed or go_version.stdout != go_version_target
  become: true

- name: configure zsh plugins
  lineinfile:
    dest: ~/.zshrc
    regexp: "^  {{ item }}$"
    insertafter: "^plugins=\\("
    line: "  {{ item }}"
    state: present
  with_items:
    - golang

- lineinfile:
    path: ~/.zshrc
    line: "{{ item }}"
  with_items:
    - export PATH="$PATH:/usr/local/go/bin"
    - export GOPATH="$HOME"

- name: install vscode extensions
  shell: "which code && code --install-extension 'ms-vscode.go'"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
