- name: setup laptop
  hosts: laptop
  roles:
    - role: remove-amazon
    - role: disable-systemd-resolved
    - role: chrome
    - role: vscode
    - role: zsh
    - role: git
    - role: keepass
    - role: docker
    - role: htop
    - role: kubectl
    - role: minikube
    - role: helm
    - role: tools
    - role: golang
    - role: slack
    - role: syncthing
    - role: java-ide
    - role: virtualbox
    - role: vagrant
