
---

- name: add apt key
  become: true
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A2F683C52980AECF

- name: add repo
  become: true
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    update_cache: yes
    filename: wolfgang42-vagrant

- name: install package
  become: true
  apt:
    pkg: vagrant
    state: latest
