
---
- name: create tmp folder for download
  file:
   path: /tmp/vagrant
   recurse: yes
   state: directory

- name:  download vagrant package
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
    dest: /tmp/vagrant/vagrant_{{ vagrant_version }}_x86_64.deb
    force: no
    validate_certs: no

- name: Install package
  become: true
  apt:
    deb=/tmp/vagrant/vagrant_{{ vagrant_version }}_x86_64.deb
    state=present

- name: cleanup download tmp folder
  file:
    state: absent
    path: "/tmp/vagrant/"
