

- name: add repo
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_10.x bionic main
    update_cache: yes
    filename: nodesource

- name: install node
  become: true
  apt:
    pkg: nodejs
    state: latest

- name: configure zsh
  lineinfile:
    path: ~/.zshrc
    line: "{{ item }}"
  with_items:
    - unalias gr
    - . <(gr completion)

- name: install git-repository-management-tool via npm
  become: true
  npm:
    name: git-run
    global: yes
