- name: add repo key
  become: true
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: add repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    update_cache: yes

- name: install chrome
  become: true
  package:
    name: google-chrome-stable
