
- name: virtualbox - add repo key for virtualbox
  become: true
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc

- name: add virtualbox repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian xenial contrib"
    filename: "virtualbox"
    update_cache: yes

- name: install virtualbox
  become: true
  package:
    name: virtualbox
