
- name: download minikube binary
  become: true
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube-{{ kubernetes_version }}"
    mode: 0755

- name: use current minikube version
  become: true
  file:
    dest: "/usr/local/bin/minikube"
    src: "/usr/local/bin/minikube-{{ kubernetes_version }}"
    state: link

- name: configure zsh plugins
  lineinfile:
    dest: ~/.zshrc
    regexp: "^  {{ item }}$"
    insertafter: "^plugins=\\("
    line: "  {{ item }}"
    state: present
  with_items:
    - minkube

- name: install socat
  become: true
  apt:
    pkg: "socat"
