
- name: download minikube binary
  become: true
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube"
    mode: 0755

// TODO add autocompletion
