
- name: add repo key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    filename: "docker"
    update_cache: yes

- name: install docker-ce
  become: true
  package:
    name: docker-ce

- name: allow docker to user
  become: true
  user:
    append: yes
    groups: docker
    name: "{{ lookup('env', 'USER') }}"

# https://github.com/docker/compose/releases
- name: download docker-compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose-{{ docker_compose_version }}
    mode: a+rx

- name: use current docker-compose version
  become: true
  file:
    dest: "/usr/local/bin/docker-compose"
    src: "/usr/local/bin/docker-compose-{{ docker_compose_version }}"
    state: link

- name: configure zsh plugins
  lineinfile:
    dest: ~/.zshrc
    regexp: "^  {{ item }}$"
    insertafter: "^plugins=\\("
    line: "  {{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: install vscode extensions
  shell: "which code && code --install-extension PeterJausovec.vscode-docker"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
